[build-system]
requires = [
    'setuptools',
    'wheel',
    'numpy == 2.0.0',
    'cython >= 0.29, < 3.1; python_version >= "3.3" or python_version < "3.0"',
]
build-backend = "setuptools.build_meta"
