[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'numpy>=1.21.4; python_version == "3.9"',
    'numpy>=1.21.4; python_version == "3.10"',
    'numpy>=1.23.3; python_version == "3.11"',
    'numpy>=1.26.1; python_version >= "3.12"',
    'cython>=0.29.21,<3.1'
]
build-backend = "setuptools.build_meta"

[project]
name = "basemap"
dynamic = ["version", "optional-dependencies"]
description = "Plot data on map projections with matplotlib"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Jeff Whitaker", email = "jeffrey.s.whitaker@noaa.gov"}
]
dependencies = [
    "numpy>=1.21.4",
    "matplotlib>=3.4.0",
    "pyproj>=3.0.0"
]

[tool.setuptools]
packages = ["mpl_toolkits.basemap"]
package-dir = {"" = "src"}
py-modules = []

[tool.setuptools.package-data]
"mpl_toolkits.basemap" = ["data/*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.pyc", "**/__pycache__/*", "**/.DS_Store/*"]
