[build-system]
requires = [
    'setuptools >= 67.0, < 81.0',
    'wheel >= 0.40, < 0.46',
    'cython >= 3.0, < 3.2',
    'numpy == 2.1.0; python_version == "3.13"',
    'numpy == 2.0.0; python_version <= "3.12"',
]
build-backend = "setuptools.build_meta"

[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]

[tool.coverage.report]
exclude_also = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
