[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'numpy>=1.21.4; python_version == "3.9"',
    'numpy>=1.21.4; python_version == "3.10"',
    'numpy>=1.23.3; python_version == "3.11"',
    'numpy>=1.26.1; python_version >= "3.12"',
    'cython>=0.29.21,<3.1'
]
build-backend = "setuptools.build_meta"

[project]
name = "basemap"
dynamic = ["version"]
description = "Plot data on map projections with matplotlib"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.21.4",
    "matplotlib>=3.4.0",
    "pyproj>=3.0.0"
]
