[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'numpy==2.0.0; python_version >= "3.9"',
    'cython>=0.29.21,<3.1'
]
build-backend = "setuptools.build_meta"

[project]
name = "basemap"
dynamic = ["version", "optional-dependencies"]
description = "Plot data on map projections with matplotlib"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Jeff Whitaker", email = "jeffrey.s.whitaker@noaa.gov"}
]
dependencies = [
    "numpy>=2.0",
    "matplotlib>=3.4.0",
    "pyproj>=3.0.0",
    "packaging >= 16.0, < 25.0",
    "pyshp >= 1.2, < 2.4",
    "basemap_data >= 1.3.2, < 1.4"
]

[tool.setuptools]
packages = ["mpl_toolkits.basemap"]
package-dir = {"" = "src"}
py-modules = []

[tool.setuptools.package-data]
"mpl_toolkits.basemap" = ["data/*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.pyc", "**/__pycache__/*", "**/.DS_Store/*"]
