[build-system]
requires = [
    'setuptools >= 67.0, < 81.0',
    'wheel >= 0.40, < 0.46',
    'cython >= 3.0, < 3.2',
    'numpy == 2.1.0; python_version == "3.13"',
    'numpy == 2.0.0; python_version <= "3.12"',
]
build-backend = "setuptools.build_meta"
