[build-system]
requires = [
    'setuptools >= 67.0, < 76.0',
    'wheel >= 0.40, < 0.46',
    'cython >= 0.29.31, < 3.1',
    'numpy == 2.1.0; python_version == "3.13"',
    'numpy == 2.0.0; python_version <= "3.12"',
]
build-backend = "setuptools.build_meta"
