/* Generated by Pyrex 0.9.3 on Tue Sep  6 12:36:47 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "proj_api.h"
#include "inttypes.h"
#include "numarray/libnumarray.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "Pyrex code to provide python interfaces to PROJ.4 functions.\nMake changes to this file, not the c-wrappers that Pyrex generates.";

/* Declarations from proj4 */

staticforward PyTypeObject __pyx_type_5proj4_Proj;

struct __pyx_obj_5proj4_Proj {
  PyObject_HEAD
  char (*pjinitstring);
  double (*projpj);
  PyObject *projparams;
};

static PyTypeObject *__pyx_ptype_5proj4__numarray = 0;
static PyTypeObject *__pyx_ptype_5proj4_Proj = 0;
static double __pyx_v_5proj4__rad2dg;
static double __pyx_v_5proj4__dg2rad;

/* Implementation of proj4 */


static PyObject *__pyx_n_math;
static PyObject *__pyx_n_radians;
static PyObject *__pyx_n_degrees;

static PyObject *__pyx_n_has_key;
static PyObject *__pyx_n_units;
static PyObject *__pyx_n_m;
static PyObject *__pyx_n_keys;
static PyObject *__pyx_n_proj;
static PyObject *__pyx_n_KeyError;
static PyObject *__pyx_n_iteritems;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_str;
static PyObject *__pyx_n_join;

static PyObject *__pyx_k7p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;
static PyObject *__pyx_k15p;

static char (__pyx_k7[]) = "resetting units to meters ...";
static char (__pyx_k11[]) = "need to specify proj parameter";
static char (__pyx_k12[]) = "+";
static char (__pyx_k13[]) = "=";
static char (__pyx_k14[]) = " ";
static char (__pyx_k15[]) = "";

static int __pyx_f_5proj4_4Proj___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj___new__[] = "\n initialize a Proj class instance.\n\n Input \'projparams\' is a dictionary containing proj map\n projection control parameter key/value pairs.\n See the proj documentation (http://proj.maptools.org) for details.\n        ";
static int __pyx_f_5proj4_4Proj___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_projparams = 0;
  double (*__pyx_v_projpj);
  PyObject *__pyx_v_pjargs;
  PyObject *__pyx_v_key;
  PyObject *__pyx_v_value;
  PyObject *__pyx_v_pjinitstring;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  char (*__pyx_9);
  static char *__pyx_argnames[] = {"projparams",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_projparams)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_projparams);
  __pyx_v_pjargs = Py_None; Py_INCREF(__pyx_v_pjargs);
  __pyx_v_key = Py_None; Py_INCREF(__pyx_v_key);
  __pyx_v_value = Py_None; Py_INCREF(__pyx_v_value);
  __pyx_v_pjinitstring = Py_None; Py_INCREF(__pyx_v_pjinitstring);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":84 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_projparams, __pyx_n_has_key); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_INCREF(__pyx_n_units);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_units);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = (!__pyx_4);
  if (__pyx_5) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":85 */
    if (PyObject_SetItem(__pyx_v_projparams, __pyx_n_units, __pyx_n_m) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_1 = PyObject_GetItem(__pyx_v_projparams, __pyx_n_units); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_1, __pyx_n_m, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_4 = __pyx_4 != 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_4) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":87 */
    if (__Pyx_PrintItem(__pyx_k7p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":88 */
    if (PyObject_SetItem(__pyx_v_projparams, __pyx_n_units, __pyx_n_m) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":91 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_projparams, __pyx_n_keys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PySequence_Contains(__pyx_1, __pyx_n_proj); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_5 = !__pyx_5;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_5) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":92 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_KeyError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k11p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":93 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_v_pjargs);
  __pyx_v_pjargs = __pyx_3;
  __pyx_3 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":94 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_projparams, __pyx_n_iteritems); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_L4:;
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      break;
    }
    __pyx_3 = __Pyx_UnpackItem(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = __pyx_3;
    __pyx_3 = 0;
    __pyx_6 = __Pyx_UnpackItem(__pyx_2, 1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_6;
    __pyx_6 = 0;
    if (__Pyx_EndUnpack(__pyx_2, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":95 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_pjargs, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __pyx_3 = PyNumber_Add(__pyx_k12p, __pyx_v_key); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __pyx_6 = PyNumber_Add(__pyx_3, __pyx_k13p); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_str); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_INCREF(__pyx_v_value);
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_v_value);
    __pyx_8 = PyObject_CallObject(__pyx_3, __pyx_7); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_3 = PyNumber_Add(__pyx_6, __pyx_8); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_7 = PyNumber_Add(__pyx_3, __pyx_k14p); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_8 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_8); __pyx_8 = 0;
  }
  __pyx_L5:;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":96 */
  __pyx_3 = PyObject_GetAttr(__pyx_k15p, __pyx_n_join); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_INCREF(__pyx_v_pjargs);
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_v_pjargs);
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_v_pjinitstring);
  __pyx_v_pjinitstring = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":97 */
  Py_INCREF(__pyx_v_projparams);
  Py_DECREF(((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projparams);
  ((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projparams = __pyx_v_projparams;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":98 */
  __pyx_9 = PyString_AsString(__pyx_v_pjinitstring); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_v_projpj = pj_init_plus(__pyx_9);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":99 */
  ((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj = __pyx_v_projpj;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("proj4.Proj.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_pjargs);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_pjinitstring);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_projparams);
  return __pyx_r;
}

static PyObject *__pyx_n___class__;

static PyObject *__pyx_f_5proj4_4Proj___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj___reduce__[] = "special method that allows projlib.Proj instance to be pickled";
static PyObject *__pyx_f_5proj4_4Proj___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":103 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n___class__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projparams);
  PyTuple_SET_ITEM(__pyx_2, 0, ((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projparams);
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("proj4.Proj.__reduce__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_5proj4_4Proj_fwd_array(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj_fwd_array[] = "\n forward transformation - lons,lats to x,y.\n x, y, lons, lats are numarrays.\n        ";
static PyObject *__pyx_f_5proj4_4Proj_fwd_array(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_lons = 0;
  PyArrayObject *__pyx_v_lats = 0;
  projUV __pyx_v_projxyout;
  projUV __pyx_v_projlonlatin;
  long __pyx_v_ndim;
  long __pyx_v_i;
  double __pyx_v_u;
  double __pyx_v_v;
  double (*__pyx_v_lonsdata);
  double (*__pyx_v_latsdata);
  PyObject *__pyx_v_x;
  PyObject *__pyx_v_y;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"lons","lats",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_lons, &__pyx_v_lats)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_lons);
  Py_INCREF(__pyx_v_lats);
  __pyx_v_x = Py_None; Py_INCREF(__pyx_v_x);
  __pyx_v_y = Py_None; Py_INCREF(__pyx_v_y);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_lons), __pyx_ptype_5proj4__numarray, 1, "lons")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_lats), __pyx_ptype_5proj4__numarray, 1, "lats")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":114 */
  __pyx_v_ndim = 1;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":115 */
  __pyx_1 = __pyx_v_lons->nd;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":116 */
    __pyx_v_ndim = (__pyx_v_ndim * (__pyx_v_lons->dimensions[__pyx_v_i]));
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":117 */
  __pyx_v_lonsdata = ((double (*))__pyx_v_lons->data);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":118 */
  __pyx_v_latsdata = ((double (*))__pyx_v_lats->data);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":119 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_ndim; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":120 */
    __pyx_v_projlonlatin.u = (__pyx_v_5proj4__dg2rad * (__pyx_v_lonsdata[__pyx_v_i]));

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":121 */
    __pyx_v_projlonlatin.v = (__pyx_v_5proj4__dg2rad * (__pyx_v_latsdata[__pyx_v_i]));

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":122 */
    __pyx_v_projxyout = pj_fwd(__pyx_v_projlonlatin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":123 */
    (__pyx_v_lonsdata[__pyx_v_i]) = __pyx_v_projxyout.u;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":124 */
    (__pyx_v_latsdata[__pyx_v_i]) = __pyx_v_projxyout.v;
    __pyx_L4:;
  }
  __pyx_L5:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":125 */
  __pyx_2 = ((PyObject *)NA_vNewArray(((void (*))__pyx_v_lonsdata),tFloat64,__pyx_v_lons->nd,__pyx_v_lons->dimensions)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_v_x);
  __pyx_v_x = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":126 */
  __pyx_2 = ((PyObject *)NA_vNewArray(((void (*))__pyx_v_latsdata),tFloat64,__pyx_v_lats->nd,__pyx_v_lats->dimensions)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_v_y);
  __pyx_v_y = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":127 */
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_x);
  Py_INCREF(__pyx_v_y);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_y);
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("proj4.Proj.fwd_array");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  return __pyx_r;
}

static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_True;
static PyObject *__pyx_n_False;
static PyObject *__pyx_n_fwd_array;
static PyObject *__pyx_n_len;

static PyObject *__pyx_f_5proj4_4Proj_fwd(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj_fwd[] = "\n forward transformation - lons,lats to x,y.\n x, y, lons, lats can be scalars, sequences or numarrays.\n        ";
static PyObject *__pyx_f_5proj4_4Proj_fwd(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_lons = 0;
  PyObject *__pyx_v_lats = 0;
  projUV __pyx_v_projxyout;
  projUV __pyx_v_projlonlatin;
  double __pyx_v_u;
  double __pyx_v_v;
  PyObject *__pyx_v_shape;
  PyObject *__pyx_v_isnumarray;
  PyObject *__pyx_v_x;
  PyObject *__pyx_v_y;
  PyObject *__pyx_v_ndim;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  long __pyx_6;
  double __pyx_7;
  static char *__pyx_argnames[] = {"lons","lats",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_lons, &__pyx_v_lats)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_lons);
  Py_INCREF(__pyx_v_lats);
  __pyx_v_shape = Py_None; Py_INCREF(__pyx_v_shape);
  __pyx_v_isnumarray = Py_None; Py_INCREF(__pyx_v_isnumarray);
  __pyx_v_x = Py_None; Py_INCREF(__pyx_v_x);
  __pyx_v_y = Py_None; Py_INCREF(__pyx_v_y);
  __pyx_v_ndim = Py_None; Py_INCREF(__pyx_v_ndim);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":136 */
  /*try:*/ {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":137 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_lons, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L2;}
    Py_DECREF(__pyx_v_shape);
    __pyx_v_shape = __pyx_1;
    __pyx_1 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":138 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L2;}
    Py_DECREF(__pyx_v_isnumarray);
    __pyx_v_isnumarray = __pyx_1;
    __pyx_1 = 0;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":139 */
  /*except:*/ {
    __Pyx_AddTraceback("proj4.fwd");
    __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":140 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    Py_DECREF(__pyx_v_isnumarray);
    __pyx_v_isnumarray = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":141 */
  __pyx_2 = PyObject_IsTrue(__pyx_v_isnumarray); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  if (__pyx_2) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":142 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_fwd_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_INCREF(__pyx_v_lons);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_lons);
    Py_INCREF(__pyx_v_lats);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_lats);
    __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_4, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_x);
    __pyx_v_x = __pyx_1;
    __pyx_1 = 0;
    __pyx_3 = __Pyx_UnpackItem(__pyx_4, 1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_y);
    __pyx_v_y = __pyx_3;
    __pyx_3 = 0;
    if (__Pyx_EndUnpack(__pyx_4, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":144 */
    /*try:*/ {

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":145 */
      __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L5;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L5;}
      Py_INCREF(__pyx_v_lons);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_lons);
      __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L5;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_v_ndim);
      __pyx_v_ndim = __pyx_4;
      __pyx_4 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":146 */
      __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L5;}
      Py_DECREF(__pyx_v_x);
      __pyx_v_x = __pyx_1;
      __pyx_1 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":146 */
      __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L5;}
      Py_DECREF(__pyx_v_y);
      __pyx_v_y = __pyx_3;
      __pyx_3 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":147 */
      __pyx_6 = PyInt_AsLong(__pyx_v_ndim); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L5;}
      for (__pyx_5 = 0; __pyx_5 < __pyx_6; ++__pyx_5) {
        __pyx_4 = PyInt_FromLong(__pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L5;}
        Py_DECREF(__pyx_v_i);
        __pyx_v_i = __pyx_4;
        __pyx_4 = 0;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":148 */
        __pyx_1 = PyFloat_FromDouble(__pyx_v_5proj4__dg2rad); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L5;}
        __pyx_3 = PyObject_GetItem(__pyx_v_lons, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L5;}
        __pyx_4 = PyNumber_Multiply(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L5;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_7 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L5;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_v_projlonlatin.u = __pyx_7;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":149 */
        __pyx_1 = PyFloat_FromDouble(__pyx_v_5proj4__dg2rad); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L5;}
        __pyx_3 = PyObject_GetItem(__pyx_v_lats, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L5;}
        __pyx_4 = PyNumber_Multiply(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L5;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_7 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L5;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_v_projlonlatin.v = __pyx_7;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":150 */
        __pyx_v_projxyout = pj_fwd(__pyx_v_projlonlatin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":151 */
        __pyx_1 = PyObject_GetAttr(__pyx_v_x, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L5;}
        __pyx_3 = PyFloat_FromDouble(__pyx_v_projxyout.u); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L5;}
        __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L5;}
        PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L5;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":152 */
        __pyx_1 = PyObject_GetAttr(__pyx_v_y, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L5;}
        __pyx_4 = PyFloat_FromDouble(__pyx_v_projxyout.v); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L5;}
        __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L5;}
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
        __pyx_4 = 0;
        __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L5;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_L7:;
      }
      __pyx_L8:;
    }
    goto __pyx_L6;
    __pyx_L5:;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":153 */
    /*except:*/ {
      __Pyx_AddTraceback("proj4.fwd");
      __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":154 */
      __pyx_3 = PyFloat_FromDouble(__pyx_v_5proj4__dg2rad); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
      __pyx_4 = PyNumber_Multiply(__pyx_v_lons, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_7 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_v_projlonlatin.u = __pyx_7;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":155 */
      __pyx_1 = PyFloat_FromDouble(__pyx_v_5proj4__dg2rad); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_v_lats, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_7 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_v_projlonlatin.v = __pyx_7;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":156 */
      __pyx_v_projxyout = pj_fwd(__pyx_v_projlonlatin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":157 */
      __pyx_4 = PyFloat_FromDouble(__pyx_v_projxyout.u); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 157; goto __pyx_L1;}
      Py_DECREF(__pyx_v_x);
      __pyx_v_x = __pyx_4;
      __pyx_4 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":158 */
      __pyx_1 = PyFloat_FromDouble(__pyx_v_projxyout.v); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
      Py_DECREF(__pyx_v_y);
      __pyx_v_y = __pyx_1;
      __pyx_1 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L4:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":159 */
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_x);
  Py_INCREF(__pyx_v_y);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_y);
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("proj4.Proj.fwd");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_shape);
  Py_DECREF(__pyx_v_isnumarray);
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_ndim);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  return __pyx_r;
}

static PyObject *__pyx_f_5proj4_4Proj_inv_array(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj_inv_array[] = "\n inverse transformation - x,y to lons,lats\n x, y, lons, lats are numarrays.\n        ";
static PyObject *__pyx_f_5proj4_4Proj_inv_array(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_x = 0;
  PyArrayObject *__pyx_v_y = 0;
  projUV __pyx_v_projxyin;
  projUV __pyx_v_projlonlatout;
  long __pyx_v_ndim;
  long __pyx_v_i;
  double __pyx_v_u;
  double __pyx_v_v;
  double (*__pyx_v_xdata);
  double (*__pyx_v_ydata);
  PyObject *__pyx_v_lons;
  PyObject *__pyx_v_lats;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x","y",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_x, &__pyx_v_y)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  __pyx_v_lons = Py_None; Py_INCREF(__pyx_v_lons);
  __pyx_v_lats = Py_None; Py_INCREF(__pyx_v_lats);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_x), __pyx_ptype_5proj4__numarray, 1, "x")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_y), __pyx_ptype_5proj4__numarray, 1, "y")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":170 */
  __pyx_v_ndim = 1;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":171 */
  __pyx_1 = __pyx_v_x->nd;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":172 */
    __pyx_v_ndim = (__pyx_v_ndim * (__pyx_v_x->dimensions[__pyx_v_i]));
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":173 */
  __pyx_v_xdata = ((double (*))__pyx_v_x->data);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":174 */
  __pyx_v_ydata = ((double (*))__pyx_v_y->data);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":175 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_ndim; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":176 */
    __pyx_v_projxyin.u = (__pyx_v_xdata[__pyx_v_i]);

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":177 */
    __pyx_v_projxyin.v = (__pyx_v_ydata[__pyx_v_i]);

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":178 */
    __pyx_v_projlonlatout = pj_inv(__pyx_v_projxyin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":179 */
    (__pyx_v_xdata[__pyx_v_i]) = (__pyx_v_5proj4__rad2dg * __pyx_v_projlonlatout.u);

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":180 */
    (__pyx_v_ydata[__pyx_v_i]) = (__pyx_v_5proj4__rad2dg * __pyx_v_projlonlatout.v);
    __pyx_L4:;
  }
  __pyx_L5:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":181 */
  __pyx_2 = ((PyObject *)NA_vNewArray(((void (*))__pyx_v_xdata),tFloat64,__pyx_v_x->nd,__pyx_v_x->dimensions)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  Py_DECREF(__pyx_v_lons);
  __pyx_v_lons = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":182 */
  __pyx_2 = ((PyObject *)NA_vNewArray(((void (*))__pyx_v_ydata),tFloat64,__pyx_v_y->nd,__pyx_v_y->dimensions)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_DECREF(__pyx_v_lats);
  __pyx_v_lats = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":183 */
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
  Py_INCREF(__pyx_v_lons);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_lons);
  Py_INCREF(__pyx_v_lats);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_lats);
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("proj4.Proj.inv_array");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  return __pyx_r;
}

static PyObject *__pyx_n_inv_array;

static PyObject *__pyx_f_5proj4_4Proj_inv(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5proj4_4Proj_inv[] = "\n inverse transformation - x,y to lons,lats\n x, y, lons, lats can be scalars, sequences or numarrays.\n        ";
static PyObject *__pyx_f_5proj4_4Proj_inv(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_v_y = 0;
  projUV __pyx_v_projxyin;
  projUV __pyx_v_projlonlatout;
  double __pyx_v_u;
  double __pyx_v_v;
  PyObject *__pyx_v_shape;
  PyObject *__pyx_v_isnumarray;
  PyObject *__pyx_v_lons;
  PyObject *__pyx_v_lats;
  PyObject *__pyx_v_ndim;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  long __pyx_6;
  double __pyx_7;
  static char *__pyx_argnames[] = {"x","y",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_x, &__pyx_v_y)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  __pyx_v_shape = Py_None; Py_INCREF(__pyx_v_shape);
  __pyx_v_isnumarray = Py_None; Py_INCREF(__pyx_v_isnumarray);
  __pyx_v_lons = Py_None; Py_INCREF(__pyx_v_lons);
  __pyx_v_lats = Py_None; Py_INCREF(__pyx_v_lats);
  __pyx_v_ndim = Py_None; Py_INCREF(__pyx_v_ndim);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":192 */
  /*try:*/ {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":193 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_x, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L2;}
    Py_DECREF(__pyx_v_shape);
    __pyx_v_shape = __pyx_1;
    __pyx_1 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":194 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L2;}
    Py_DECREF(__pyx_v_isnumarray);
    __pyx_v_isnumarray = __pyx_1;
    __pyx_1 = 0;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":195 */
  /*except:*/ {
    __Pyx_AddTraceback("proj4.inv");
    __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":196 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
    Py_DECREF(__pyx_v_isnumarray);
    __pyx_v_isnumarray = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":197 */
  __pyx_2 = PyObject_IsTrue(__pyx_v_isnumarray); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  if (__pyx_2) {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":198 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_inv_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    Py_INCREF(__pyx_v_x);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_x);
    Py_INCREF(__pyx_v_y);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_y);
    __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_4, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    Py_DECREF(__pyx_v_lons);
    __pyx_v_lons = __pyx_1;
    __pyx_1 = 0;
    __pyx_3 = __Pyx_UnpackItem(__pyx_4, 1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    Py_DECREF(__pyx_v_lats);
    __pyx_v_lats = __pyx_3;
    __pyx_3 = 0;
    if (__Pyx_EndUnpack(__pyx_4, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":200 */
    /*try:*/ {

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":201 */
      __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L5;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L5;}
      Py_INCREF(__pyx_v_x);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_x);
      __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L5;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_v_ndim);
      __pyx_v_ndim = __pyx_4;
      __pyx_4 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":202 */
      __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L5;}
      Py_DECREF(__pyx_v_lons);
      __pyx_v_lons = __pyx_1;
      __pyx_1 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":202 */
      __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L5;}
      Py_DECREF(__pyx_v_lats);
      __pyx_v_lats = __pyx_3;
      __pyx_3 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":203 */
      __pyx_6 = PyInt_AsLong(__pyx_v_ndim); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L5;}
      for (__pyx_5 = 0; __pyx_5 < __pyx_6; ++__pyx_5) {
        __pyx_4 = PyInt_FromLong(__pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L5;}
        Py_DECREF(__pyx_v_i);
        __pyx_v_i = __pyx_4;
        __pyx_4 = 0;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":204 */
        __pyx_1 = PyObject_GetItem(__pyx_v_x, __pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L5;}
        __pyx_7 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L5;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_v_projxyin.u = __pyx_7;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":205 */
        __pyx_3 = PyObject_GetItem(__pyx_v_y, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L5;}
        __pyx_7 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L5;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_v_projxyin.v = __pyx_7;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":206 */
        __pyx_v_projlonlatout = pj_inv(__pyx_v_projxyin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":207 */
        __pyx_4 = PyObject_GetAttr(__pyx_v_lons, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L5;}
        __pyx_1 = PyFloat_FromDouble((__pyx_v_projlonlatout.u * __pyx_v_5proj4__rad2dg)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L5;}
        __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L5;}
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
        __pyx_1 = 0;
        __pyx_1 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L5;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;

        /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":208 */
        __pyx_4 = PyObject_GetAttr(__pyx_v_lats, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L5;}
        __pyx_3 = PyFloat_FromDouble((__pyx_v_projlonlatout.v * __pyx_v_5proj4__rad2dg)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L5;}
        __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L5;}
        PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L5;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_L7:;
      }
      __pyx_L8:;
    }
    goto __pyx_L6;
    __pyx_L5:;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;

    /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":209 */
    /*except:*/ {
      __Pyx_AddTraceback("proj4.inv");
      __pyx_4 = __Pyx_GetExcValue(); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":210 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
      __pyx_v_projxyin.u = __pyx_7;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":211 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
      __pyx_v_projxyin.v = __pyx_7;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":212 */
      __pyx_v_projlonlatout = pj_inv(__pyx_v_projxyin,((struct __pyx_obj_5proj4_Proj *)__pyx_v_self)->projpj);

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":213 */
      __pyx_1 = PyFloat_FromDouble((__pyx_v_projlonlatout.u * __pyx_v_5proj4__rad2dg)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
      Py_DECREF(__pyx_v_lons);
      __pyx_v_lons = __pyx_1;
      __pyx_1 = 0;

      /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":214 */
      __pyx_3 = PyFloat_FromDouble((__pyx_v_projlonlatout.v * __pyx_v_5proj4__rad2dg)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L1;}
      Py_DECREF(__pyx_v_lats);
      __pyx_v_lats = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L4:;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":215 */
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
  Py_INCREF(__pyx_v_lons);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_lons);
  Py_INCREF(__pyx_v_lats);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_lats);
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("proj4.Proj.inv");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_shape);
  Py_DECREF(__pyx_v_isnumarray);
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  Py_DECREF(__pyx_v_ndim);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_False, "False"},
  {&__pyx_n_KeyError, "KeyError"},
  {&__pyx_n_True, "True"},
  {&__pyx_n___class__, "__class__"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_degrees, "degrees"},
  {&__pyx_n_fwd_array, "fwd_array"},
  {&__pyx_n_has_key, "has_key"},
  {&__pyx_n_inv_array, "inv_array"},
  {&__pyx_n_iteritems, "iteritems"},
  {&__pyx_n_join, "join"},
  {&__pyx_n_keys, "keys"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_m, "m"},
  {&__pyx_n_math, "math"},
  {&__pyx_n_proj, "proj"},
  {&__pyx_n_radians, "radians"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_str, "str"},
  {&__pyx_n_units, "units"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, __pyx_k15, sizeof(__pyx_k15)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_5proj4_Proj(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5proj4_Proj *p = (struct __pyx_obj_5proj4_Proj *)o;
  p->projparams = Py_None; Py_INCREF(p->projparams);
  if (__pyx_f_5proj4_4Proj___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_5proj4_Proj(PyObject *o) {
  struct __pyx_obj_5proj4_Proj *p = (struct __pyx_obj_5proj4_Proj *)o;
  Py_XDECREF(p->projparams);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5proj4_Proj(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5proj4_Proj *p = (struct __pyx_obj_5proj4_Proj *)o;
  if (p->projparams) {
    e = (*v)(p->projparams, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5proj4_Proj(PyObject *o) {
  struct __pyx_obj_5proj4_Proj *p = (struct __pyx_obj_5proj4_Proj *)o;
  Py_XDECREF(p->projparams);
  p->projparams = Py_None; Py_INCREF(p->projparams);
  return 0;
}

static struct PyMethodDef __pyx_methods_5proj4_Proj[] = {
  {"__reduce__", (PyCFunction)__pyx_f_5proj4_4Proj___reduce__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5proj4_4Proj___reduce__},
  {"fwd_array", (PyCFunction)__pyx_f_5proj4_4Proj_fwd_array, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5proj4_4Proj_fwd_array},
  {"fwd", (PyCFunction)__pyx_f_5proj4_4Proj_fwd, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5proj4_4Proj_fwd},
  {"inv_array", (PyCFunction)__pyx_f_5proj4_4Proj_inv_array, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5proj4_4Proj_inv_array},
  {"inv", (PyCFunction)__pyx_f_5proj4_4Proj_inv, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5proj4_4Proj_inv},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Proj = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Proj = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Proj = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Proj = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_5proj4_Proj = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "proj4.Proj", /*tp_name*/
  sizeof(struct __pyx_obj_5proj4_Proj), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5proj4_Proj, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Proj, /*tp_as_number*/
  &__pyx_tp_as_sequence_Proj, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Proj, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Proj, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5proj4_Proj, /*tp_traverse*/
  __pyx_tp_clear_5proj4_Proj, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5proj4_Proj, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5proj4_Proj, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initproj4(void); /*proto*/
DL_EXPORT(void) initproj4(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  double __pyx_4;
  __pyx_m = Py_InitModule4("proj4", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_ptype_5proj4__numarray = __Pyx_ImportType("numarray._numarray", "_numarray", sizeof(PyArrayObject)); if (!__pyx_ptype_5proj4__numarray) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_type_5proj4_Proj.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5proj4_Proj) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Proj", (PyObject *)&__pyx_type_5proj4_Proj) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_ptype_5proj4_Proj = &__pyx_type_5proj4_Proj;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":4 */
  __pyx_1 = __Pyx_Import(__pyx_n_math, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_math, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":7 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_math); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_radians); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyFloat_FromDouble(1.); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_5proj4__dg2rad = __pyx_4;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":8 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_math); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_degrees); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyFloat_FromDouble(1.); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_5proj4__rad2dg = __pyx_4;

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":66 */
  import_libnumarray();

  /* "/Volumes/User/jsw/python/matplotlib/basemap_cvs/toolkits/basemap/src/proj4.pyx":185 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("proj4");
}

static char *__pyx_filenames[] = {
  "proj4.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        int len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, int i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, int i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
