name: Build and Test

env:
  PKGDIR: "packages/basemap"
  CIBW_BUILD_VERBOSITY: 1
  PYTHONUNBUFFERED: "1"
  PYTHONWARNINGS: "ignore:DEPRECATION"
  GEO_VERSION: "3.6.5"

on:
  push:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.16.x"

      - name: Setup C++ toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Setup C++ toolchain (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup C++ toolchain (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || true

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        env:
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_BEFORE_BUILD: >
            python -c "import utils; utils.GeosLibrary('${{ env.GEO_VERSION }}').build('extern', njobs=16)"
          CIBW_ENVIRONMENT: >
            GEOS_DIR=/project/packages/basemap/extern
            CPATH=/project/packages/basemap/extern/include
            LIBRARY_PATH=/project/packages/basemap/extern/lib
            LD_LIBRARY_PATH=/project/packages/basemap/extern/lib
            SETUPTOOLS_USE_DISTUTILS=stdlib
          CIBW_TEST_COMMAND: >
            cd {project} && python -m pytest --cov="mpl_toolkits.basemap"
            --cov-report=term --ignore=dist --ignore=build
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
        run: |
          cd ${{ env.PKGDIR }}
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ${{ env.PKGDIR }}/wheelhouse/*.whl
