name: Build Data Packages

env:
  PYTHONUNBUFFERED: "1"
  PYTHONWARNINGS: "ignore:DEPRECATION"

on:
  push:
    paths:
      - "packages/basemap_data/**"
      - "packages/basemap_data_hires/**"
  pull_request:
    paths:
      - "packages/basemap_data/**"
      - "packages/basemap_data_hires/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [basemap_data, basemap_data_hires]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Build package
        run: |
          cd packages/${{ matrix.package }}
          pip install build
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.package }}
          path: packages/${{ matrix.package }}/dist/*

  upload_testpypi:
    needs: [build]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        package: [basemap_data, basemap_data_hires]
    environment:
      name: TestPyPI
      url: https://test.pypi.org/p/${{ matrix.package }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.package }}
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  upload_pypi:
    needs: [build, upload_testpypi]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        package: [basemap_data, basemap_data_hires]
    environment:
      name: PyPI
      url: https://pypi.org/p/${{ matrix.package }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.package }}
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
