name: Build

on:
  push:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
      - "packages/basemap_data/**"
      - "packages/basemap_data_hires/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
      - "packages/basemap_data/**"
      - "packages/basemap_data_hires/**"
  workflow_dispatch:

jobs:
  build_data:
    name: Build data packages
    strategy:
      matrix:
        package: [basemap_data, basemap_data_hires]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Build sdist and wheels
        run: |
          cd packages/${{ matrix.package }}
          python -m pip install build wheel
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          path: |
            packages/${{ matrix.package }}/dist/*.tar.gz
            packages/${{ matrix.package }}/dist/*.whl
          name: dist-${{ matrix.package }}

  build_sdist:
    name: Build basemap sdist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Build sdist
        run: |
          cd packages/basemap
          python -m pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: packages/basemap/dist/*.tar.gz
          name: dist-basemap-sdist

  build_wheels:
    name: Build basemap wheels
    needs: [build_data, build_sdist]
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Download data packages
        uses: actions/download-artifact@v4
        with:
          pattern: dist-basemap_data*
          path: ./data_packages/
          merge-multiple: true

      - name: Install data packages (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Install the wheel data packages with wildcard
          python -m pip install ./data_packages/*.whl

          # Verify that the data packages can be imported
          python -c "import mpl_toolkits.basemap_data; print('mpl_toolkits.basemap_data installed successfully')"

      - name: Install data packages (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Install the wheel data packages sequentially
          $wheels = Get-ChildItem -Path "./data_packages" -Filter "*.whl" -Recurse
          foreach ($wheel in $wheels) {
            Write-Host "Installing $($wheel.FullName)"
            python -m pip install $wheel.FullName
          }

          # Verify that the data packages can be imported
          python -c "import mpl_toolkits.basemap_data; print('mpl_toolkits.basemap_data installed successfully')"

      - name: Download basemap sdist
        uses: actions/download-artifact@v4
        with:
          name: dist-basemap-sdist
          path: ./sdist/

      - name: Extract sdist (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Create extraction directory in the workspace
          mkdir -p ./sdist_extract

          # Extract with tar using wildcard
          tar -xvf ./sdist/*.tar.gz -C ./sdist_extract

          # Get the extracted directory name
          EXTRACTED_DIR="$(ls -d ./sdist_extract/*/ | head -1)"

          # Verify contents
          ls -la "${EXTRACTED_DIR}"

          # Set the environment variable
          echo "SDIST_DIR=$(pwd)/${EXTRACTED_DIR}" >> $GITHUB_ENV

      - name: Extract sdist (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Create extraction directory in the workspace
          New-Item -ItemType Directory -Force -Path "sdist_extract"

          # Extract with tar using the specific file path (no wildcard)
          $tarball = Get-ChildItem -Path "sdist" -Filter "*.tar.gz" | Select-Object -First 1
          tar -xvf $tarball.FullName -C "sdist_extract"

          # Get the extracted directory name
          $extractedDir = (Get-ChildItem -Path "sdist_extract" -Directory | Select-Object -First 1).FullName

          # Verify contents
          Get-ChildItem "$extractedDir"

          # Set the environment variable
          echo "SDIST_DIR=$extractedDir" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build wheels from sdist
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: "native"
          CIBW_BUILD: "cp39* cp310* cp311* cp312* cp313*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BEFORE_ALL: "python {project}/.github/workflows/run_before_all.py"
          CIBW_TEST_EXTRAS: "test"
          CIBW_TEST_COMMAND: "python -m pytest {project}/packages/basemap"
          CIBW_ENVIRONMENT: >-
            GEOS_VERSION="3.6.5"
            GEOS_DIR="$(pwd)/extern"
            GEOS_NJOBS=4
            PIP_PREFER_BINARY=1
            PYTHONUNBUFFERED=1
            LD_LIBRARY_PATH="${GEOS_DIR}/lib"
          # LD_LIBRARY_PATH in environment is needed by
          # auditwheel (Linux) and delocate (MacOS).
        with:
          package-dir: ${{ env.SDIST_DIR }}
          output-dir: "dist"
          # Set `package-dir` to a folder with the extracted sdist;
          # otherwise, `cibuildwheel` uses `python -m pip wheel` or
          # `python -m build --wheel` with the repository package
          # folder and we cannot guarantee that wheels can be built
          # from the sdist.

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
          name: dist-basemap-wheels-${{ matrix.os }}

  check:
    name: Check packages
    needs: [build_data, build_sdist, build_wheels]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "dist-*"
          merge-multiple: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Check packages with twine
        run: |
          python -m pip install twine
          python -m twine check dist/*.tar.gz
          python -m twine check dist/*.whl

  upload:
    name: Upload packages
    needs: [build_data, build_sdist, build_wheels, check]
    runs-on: ubuntu-22.04
    environment: PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "dist-*"
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: ${{ secrets.PYPI_REPOSITORY_URL }}
          skip-existing: true
